name: Github CI pipeline testing the html file
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate HTML file
        run: |
          if [ -f "index.html" ]; then
            echo "HTML file exists."
          else
            echo "HTML file does not exist."
            exit 1
          fi
